# Generated by Django 5.0 on 2024-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pysteamapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jeux',
            new_name='Jeu',
        ),
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('Jeu', models.ManyToManyField(blank=True, to='pysteamapp.jeu')),
            ],
        ),
        migrations.DeleteModel(
            name='BibliothequeDeJeux',
        ),
    ]
