# Generated by Django 5.0 on 2024-03-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pysteamapp', '0002_rename_jeux_jeu_bibliotheque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliotheque',
            old_name='Jeu',
            new_name='jeux',
        ),
    ]
