name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        apt -y update
        curl -sS https://bootstrap.pypa.io/get-pip.py | python
        pip3.12 install -r requirements.txt
    - name: Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py check
    - name: Run Tests
      run: |
        python manage.py test