name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up GeckoDriver [latest]
      uses: browser-actions/setup-geckodriver@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test version GeckoDriver
      run: geckodriver --version
    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox-esr
    - name: Install Dependencies
      run: |
        apt -y update
        apt -y install libsqlite3-0
        apt -y install curl
        curl -sS https://bootstrap.pypa.io/get-pip.py | python
        pip3.12 install -r requirements.txt
    - name: Install Selenium
      run: pip3.12 install --upgrade selenium
    - name: Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py check
    - name: Run Tests
      run: |
        python manage.py test
        python manage.py test pysteamapp.testviews
        python manage.py test pysteamapp.testselenium